### ISSUE TITLE
DataFormatException: [element="status"] Invalid attribute value "completed": Unknown DiagnosticReportStatus code 'completed'

### ISSUE THREAD

**Issue by russellbateman-perfectsearchcorp** [MDMI/Getting-Started#6]
In FHIR, a resource's status code values are specific to that resource. For instance, see line 94:

```
86       "resource": {
87         "resourceType": "DiagnosticReport",
88         "identifier": [
89           {
90             "system": "0570ea1d-2f4b-4acf-ad4f-022cacd303da",
91             "value": "0570ea1d-2f4b-4acf-ad4f-022cacd303da"
92          }
93         ],
94         "status": "completed",
95        "code": {
96           "coding": [
97             {
98               "system": "2.16.840.1.113883.6.1",
99               "code": "_1552116",
```
 isn't valid for a _DiagnosticReport_ resource, but requires a value (proabably, "final") from _DiagnosticReport_ status (see https://www.hl7.org/fhir/valueset-diagnostic-report-status.html).

This affects several other resources all of whose status fields are either "completed" or "active." Many resources' status field needing "active" are instead, "in-progress."

**Comment by swmuir** [comment]
We will need to set up concept maps and URIs
